- fail:
    msg: You need to specify exactly one host to run the editor.
  when: "{{ groups.editor|length != 1}}"

- name: Add server name to the apache.conf
  lineinfile:
      dest: "/etc/apache2/apache2.conf"
      regexp: ^ServerName
      line: "ServerName {{ inventory_hostname }}"
      state: present
  notify:
      - restart apache2

- name: Ensure locale is en_US.UTF-8
  lineinfile:
      dest: /etc/default/locale
      regexp: LC_ALL
      line: "LC_ALL=\"en_US.UTF-8\""

- name: Install required packages
  apt:
      name: "{{ item }}"
      state: latest
  with_items:
      - git
      # Galaxy needs python 2.7.
      - python
      - virtualenv
      - postgresql
      - postgresql-contrib
      - python-psycopg2

- name: "Clone galaxy repo {{galaxy_repo}} repo"
  git:
      repo: "{{ galaxy_repo }}"
      dest: "{{ editor_directory }}"
      clone: yes
      version: "{{ galaxy_version }}"
      accept_hostkey: yes

- name: Install extra packages in virtualenv
  pip: name="{{ item }}" virtualenv="{{ editor_directory }}/.venv"
  with_items:
    - watchdog

- name: Create postgres user and database
  become: yes
  become_user: postgres
  shell: |
    createuser {{ editor_db_user }}
    createdb {{ editor_db_name }}
    psql -c "ALTER USER {{ editor_db_user }} WITH ENCRYPTED PASSWORD  '{{ editor_db_password }}';"
  tags: postgres

- name: Create tool_conf.xml file
  copy:
      remote_src: True
      src: "{{ editor_directory }}/config/tool_conf.xml.sample"
      dest: "{{ editor_directory }}/config/tool_conf.xml"

- name: Setup galaxy.ini
  template:
    src: galaxy.ini.j2
    dest: "{{ editor_directory }}/config/galaxy.ini"
    force: yes

- name: Setup systemd
  template:
    src: galaxy.service.j2
    dest: "/lib/systemd/system/galaxy.service"
    force: yes

- name: Install Galaxy
  shell: "{{editor_directory}}/run.sh --status | echo OK"

- name: Enable Galaxy in systemd
  shell: "systemctl enable galaxy"
  notify: start galaxy
