- hosts: all
  remote_user: root
  gather_facts: no
  tasks:
      - name: Install python
        raw: "apt-get update -y && apt-get install {{ python_package }} -y"
        when: "{{ install_python }}"

- hosts: docker_registry
  remote_user: root
  roles:
      - lexrus.ansible-role-docker
      - role: docker-registry
      - geerlingguy.apache

- hosts: cluster_master
  remote_user: root
  roles:
      - role: mesos-master
      - role: chronos

- hosts: cluster_nodes
  remote_user: root
  pre_tasks:
    - set_fact:
        data_share: "{{ hostvars[groups['executor'][0]].data_share }}"
  roles:
      - lexrus.ansible-role-docker
      - role: mesos-slaves
      - role: nfs-cluster-clients

- hosts: executor
  remote_user: root
  roles:
      - lexrus.ansible-role-docker
      - role: executor
      - role: nfs
      - geerlingguy.apache

- hosts: monitor
  remote_user: root
  roles:
      - geerlingguy.apache
      - role: prometheus

- hosts: editor
  remote_user: root
  pre_tasks:
    - set_fact:
        tools_share: "{{ hostvars[groups['executor'][0]].tools_share }}"
  roles:
      - role: editor
      - geerlingguy.apache
