- fail:
    msg: You need to specify exactly one host running Galaxy.
  when: "{{ groups.galaxy|length != 1}}"

- name: Add server name to the apache.conf
  lineinfile:
      dest: "/etc/apache2/apache2.conf"
      regexp: ^ServerName
      line: "ServerName {{ inventory_hostname }}"
      state: present
  notify:
      - restart apache2

- name: Ensure locale is en_US.UTF-8
  lineinfile:
      dest: /etc/default/locale
      regexp: LC_ALL
      line: "LC_ALL=\"en_US.UTF-8\""

- name: Install required packages
  apt:
      name: "{{ item }}"
      state: latest
  with_items:
      - git
      # Galaxy needs python 2.7.
      - python
      - virtualenv

- name: Clone galaxy repo
  git:
      repo: "{{ galaxy_repo }}"
      dest: "{{ galaxy_directory }}"
      clone: yes
      version: "{{ galaxy_version }}"
      accept_hostkey: yes

- name: Install watchdog python package
  pip: name=watchdog virtualenv={{ galaxy_directory }}/.venv

- name: Create object store
  file:
      path: "{{ object_store_directory }}"
      state: directory

- name: Create galaxy.ini file
  copy:
      remote_src: True
      src: "{{ galaxy_directory }}/config/galaxy.ini.sample"
      dest: "{{ galaxy_directory }}/config/galaxy.ini"

- name: Set job working directory 
  lineinfile:
      dest: "{{ galaxy_directory }}/config/galaxy.ini"
      regexp: ^(#?)+job_working_directory\s?=
      line: "job_working_directory = {{ object_store_directory }}/{{ job_working_directory }}"
      state: present

- name: Set file directory
  lineinfile:
      dest: "{{ galaxy_directory }}/config/galaxy.ini" 
      regexp: ^(#?)+file_path\s?=
      line: "file_path = {{ object_store_directory }}/{{ files_directory }}"
      state: present

- name: Set tmp directory 
  lineinfile:
      dest: "{{ galaxy_directory }}/config/galaxy.ini"
      regexp: ^(#?)+new_file_path\s?=
      line: "new_file_path = {{ object_store_directory }}/{{ tmp_directory }}"
      state: present

- name: Create tool_conf.xml file
  copy:
      remote_src: True
      src: "{{ galaxy_directory }}/config/tool_conf.xml.sample"
      dest: "{{ galaxy_directory }}/config/tool_conf.xml"
