- name: Install Mesos
  apt:
      name: mesos
      state: latest
  register: mesos_installed

- name: Disable Zookeeper and mesos-master services
  service:
      name: "{{ item }}"
      enabled: no
      state: stopped
  with_items:
      - zookeeper
      - mesos-master

- name: Create /etc/mesos-slave/store directory
  file:
    path: /etc/mesos-slave/store
    state: directory
    recursive: yes

- name: Set credentials
  template:
    src: credentials.json.j2
    dest: "/etc/mesos-slave/store/credentials.json"
    force: yes

- name: Copy configuration files
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    force: yes
    owner: root
  with_items:
    - { content: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}", dest: "/etc/mesos-slave/ip" }
    - { content: "{{ inventory_hostname }}", dest: "/etc/mesos-slave/hostname" }
    - { content: "docker,mesos", dest: "/etc/mesos-slave/containerizers" }
    - { content: "5mins", dest: "/etc/mesos-slave/executor_registration_timeout" }
    - { content: "/etc/mesos-slave/store/credentials.json", dest: "/etc/mesos-slave/credentials" }
  notify:
    - restart mesos-slave

- debug: msg="{{ cluster_nodes[inventory_hostname] }}"
