server_root: /usr/local/apache2

apache_global_vhost_settings: ServerRoot "{{ server_root }}"
apache_remove_default_vhost: True

apache_vhosts:
  - servername: "{{ inventory_hostname }}"
  - extra_parameters: |
        Header always set "Docker-Distribution-Api-Version" "registry/2.0"
        Header onsuccess set "Docker-Distribution-Api-Version" "registry/2.0"
        RequestHeader set X-Forwarded-Proto "https"
        ProxyRequests     off
        ProxyPreserveHost on
        ProxyPass /error/ !
        ProxyPass        /v2 http://127.0.0.1:5000/v2
        ProxyPassReverse /v2 http://127.0.0.1:5000/v2
        <Location /v2>
            Order deny,allow
            Allow from all
            AuthName "Registry Authentication"
            AuthType basic
            AuthUserFile "{{ server_root }}/conf/htpasswd"

            # Read access to authentified users
            <Limit GET HEAD>
                    Require valid-user
            </Limit>
        </Location>
