- name: restart mesos-master
  service:
      name: mesos-master
      enabled: yes
      state: restarted
  when: "{{ inventory_hostname in groups.mesos_masters and (mesos_installed is defined and mesos_installed) }}"

- name: restart mesos-slave
  service:
      name: mesos-slave
      enabled: yes
      state: restarted
  when: "{{ inventory_hostname in groups.mesos_slaves and (mesos_installed is defined and mesos_installed) }}"

- name: restart chronos
  service:
      name: chronos
      enabled: yes
      state: restarted
  when: "{{ inventory_hostname in groups.chronos and (chronos_installed is defined and chronos_installed) }}"
