- name: restart zookeeper
  service:
      name: zookeeper
      enabled: yes
      state: restarted

- name: restart mesos
  service:
      name: mesos-master
      enabled: yes
      state: restarted
  when: "{{ inventory_hostname in groups.mesos_masters }}"
