- name: Install nfs-client
  apt:
      name: nfs-common
      state: latest

- name: Create mountable directory
  file:
      path: "{{ data_share }}"
      state: directory

- name: Create mount points
  mount:
      name: "{{ data_share }}"
      src: "{{ groups.executor[0] }}:{{ data_share }}"
      state: mounted
      fstype: nfs
