mesosphere_repo: "deb http://repos.mesosphere.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
fqdn: "{{ hostvars[inventory_hostname].ansible_nodename }}.{{ hostvars[inventory_hostname].ansible_dns.domain }}"