mesosphere_repo: "deb http://repos.mesosphere.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
domain: "{% if 'domain' in hostvars[inventory_hostname].ansible_dns %}\
  {{ hostvars[inventory_hostname].ansible_dns.domain}}\
  {% else %}\
  {{ hostvars[inventory_hostname].ansible_dns.search[0]}}\
  {% endif %}"
fqdn: "{{ hostvars[inventory_hostname].ansible_nodename }}.{{ domain }}"