- name: Add apt-key
  apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: E56151BF
      state: present

- name: Add Mesosphere repository
  apt_repository:
      repo: "{{ mesosphere_repo }}"
      state: present
      filename: mesosphere
      update_cache: yes

- name: Point to the Zookeeper Quorum
  template:
      src: zk.j2
      dest: /etc/mesos/zk
      force: yes
  notify:
      # OK, it's quite dirty.
      - restart mesos-master
      - restart mesos-slave
      - restart chronos
